# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2016
  project: T3Blog Extbase
  version: 2.2.0
  release: 2.2.0
  latex_documents:
  - - Index
    - t3extblog.tex
    - T3Blog Extbase
    - Felix Nagel
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    restdoc:
    - http://docs.typo3.org/typo3cms/extensions/restdoc/
    - null
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    t3cmsapi:
    - http://typo3.org/api/typo3cms/
    - null
  extlinks:
    ter:
    - http://www.typo3.org/extensions/repository/view/%s
    - 'TYPO3 extension '
  extensions:
  - sphinx.ext.intersphinx
  - t3sphinx.ext.t3extras
  - t3sphinx.ext.t3tablerows
  - t3sphinx.ext.targets
  - sphinx.ext.extlinks
...
